export const PurchaseStyle = {
    container: {
        backgroundColor: 'rgb(255, 255, 255)',
        color: 'rgb(97, 97, 97)',
        transition: 'boxShadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
        borderRadius: '7px',
        overflow: 'hidden',
        border: '1px solid rgba(144, 202, 249, 0.46)',
        height: 'max-content',
        padding:'30px',
        margin: '0px 20px',
    },
    filtercontainer:{
        backgroundColor: 'rgb(255, 255, 255)',
        color: 'rgb(97, 97, 97)',
        transition: 'boxShadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms',
        borderRadius: '12px',
        overflow: 'hidden',
        border: '1px solid rgba(144, 202, 249, 0.46)',
        padding:'15px',
         height: 'max-content',
         margin: '0px 20px',
    },
    button_add: {
        backgroundColor: '#7009ab !important',
        color: 'white',
        marginRight: '5px !important',
        height: '40px !important',
        padding: '10px !important',
        fontWeight: '600 !important',
        borderRadius: '7px !important',
        float: 'right !important',
        border: '0px !important',
        '&:hover' : {
            backgroundColor: '#fff !important',
            border: '1px solid #7009ab !important',
            color: '#a5becc !important',
        },
    },
    button_grp : {
        backgroundColor: 'rgb(245 243 246) !important',
        color: '#7009AB !important',
        borderColor: '#ddd !important',
        margin: '1px !important',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        fontSize: '12px !important',
    },
    grid_container:{
        justifyContent:'center',
    },
    UnitHeaderText:{
        fontFamily:"'Source Sans Pro','Helvetica Neue',Helvetica,Arial,sans-serif",
        fontSize: "23px",
        fontWeight: "400",
        margin:"10px 30px",
        color: "#384460 !important",
    },
    tablecontainer:{
        border:'none',
        boxShadow:'none',
    },
    spanInfoIcons : {
        fontSize: '16px', 
        paddingTop: '0px !important', 
        paddingLeft: '1px',
        paddingRight: '2px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px !important', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
    spanIcons : {
        fontSize: '16px', 
        paddingTop: '7px !important', 
        paddingLeft: '11px',
        paddingRight: '1px',
        margin: 'auto', 
        border: '1px solid #b97df0', 
        width: '45px !important', 
        height: '40px', 
        backgroundColor: 'white', 
        color: '#7009ab' ,
    },
}